### ISSUE TITLE
Первоначальный период ожидания в 2 секунды может иметь неопределенную длительность.

### ISSUE THREAD

**Issue by mak22223** [AlexGyver/WebLamp#4]
В строке 24 вызывается метод `elapsed()`, который в свою очередь вызывает метод `check()`. Метод `check()` сравнивает значение `millis() - prd` с `tmr`, где `tmr` является неинициализированной переменной либо из-за ошибки в конструкторе класса Timer из мини-библиотеки Timer.h, либо из-за отсутствия вызова метода `restart()` у объекта таймера. 

По логике надо вообще проверять результат метода `elapsed()` после запуска таймера, а не `period()`.

https://github.com/AlexGyver/WebLamp/blob/1fd88590afb976f4e32f74cecf482c0882cebbb7/firmware/WebLamp_v1.0/startup.ino#L21-L27

**Comment by AlexGyver** [comment]
Согласен, добавил инициализацию в конструктор
